version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "elasticbeanstalk-us-west-2-277014642641"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --env=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp angular4Dogpark s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'angular4Dogpark*'
    discard-paths: yes